<?php
$lang = array(
    // MENÚ Y FOOTER
    "conocenos" => "Conócenos",
    "productos" => "Productos",
    "carrito" => "Carrito",
    "perfil" => "Mi Perfil",
    "login" => "Iniciar Sesión",
    "logout" => "Cerrar Sesión",
    "registro" => "Registrarse",
    "enlaces" => "Enlaces rápidos",
    "contacto" => "Contacto",
    "aviso" => "Aviso Legal",
    "privacidad" => "Política de Privacidad",
    "cookies" => "Política de Cookies",

    // PÁGINA DE INICIO (INDEX)
    "index_titulo" => "Inicio Visitante - Metalful",
    "hero_titulo" => "Metalistería con más de 30 años de experiencia en el sector",
    "donde_estamos" => "Donde nos encontramos",
    "direccion" => "Extrarradio Cortijo la Purisima, 2P, 18004 Granada",
    "problemas_encontrar" => "Si tiene problemas para encontrarnos llame a este número:",
    "nuestros_productos" => "Nuestros Productos",
    "ver_mas" => "Ver más",
    "faq_titulo" => "Preguntas Frecuentes",
    "faq_q1" => "¿Cuánto tarda el producto en llegar?",
    "faq_a1" => "El tiempo de entrega suele ser entre 3 y 7 días según el tipo de producto.",
    "faq_q2" => "¿Cuál es el rango de distribución de los productos?",
    "faq_a2" => "Hacemos entregas en toda la provincia de Granada y zonas cercanas.",
    "faq_q3" => "¿Cómo puede contactarnos?",
    "faq_a3" => "Puede llamarnos al 652 921 960 o escribirnos a metalfulsan@gmail.com.",

    // COOKIES BANNER
    "cookie_titulo" => "Privacidad y Cookies.",
    "cookie_desc" => "Utilizamos cookies propias para mejorar tu experiencia. Puedes aceptarlas o rechazar su uso. Lee nuestra",
    "cookie_link" => "política de cookies",
    "cookie_rechazar" => "Rechazar",
    "cookie_aceptar" => "Aceptar todo",


    // AVISO LEGAL
    "legal_titulo_pag" => "Aviso Legal - Metalistería Fulsan",
    "legal_h1" => "Aviso Legal",
    "legal_fecha" => "Última actualización: 15 de Marzo de 2024",
    "legal_intro" => "En cumplimiento del artículo 10 de la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y Comercio Electrónico (LSSICE), a continuación se exponen los datos identificativos de la entidad:",
    "legal_datos_t" => "1. Datos Identificativos",
    "legal_nombre_com" => "Nombre comercial:",
    "legal_denom_soc" => "Denominación social:",
    "legal_domicilio" => "Domicilio social:",
    "legal_correo" => "Correo electrónico:",
    "legal_tel" => "Teléfono:",
    "legal_prop_t" => "2. Propiedad Intelectual",
    "legal_prop_desc" => "El código fuente, los diseños gráficos, las imágenes, las fotografías, los sonidos, las animaciones, el software, los textos, así como la información y los contenidos que se recogen en el presente sitio web están protegidos por la legislación española sobre los derechos de propiedad intelectual e industrial a favor de Metalistería Fulsan S.L.",
    "legal_prot_t" => "3. Protección de Datos Personales",
    "legal_prot_desc" => "En el marco del cumplimiento de la legislación vigente, recogida en la Ley Orgánica 15/1999, de 13 de diciembre, sobre protección de Datos de Carácter Personal (LOPD), cuyo objeto es garantizar y proteger, en lo que concierne al tratamiento de los datos personales, las libertades y derechos fundamentales de las personas físicas, Metalistería Fulsan informa a los usuarios de que los datos introducidos en los formularios de contacto se almacenarán en un fichero automatizado propiedad de la empresa.",
    "legal_ley_t" => "4. Legislación Aplicable",
    "legal_ley_desc" => "La ley aplicable en caso de disputa o conflicto de interpretación de los términos que conforman este aviso legal, así como cualquier cuestión relacionada con los servicios del presente portal, será la ley española.",

    // CARRITO
    "carrito_titulo_pag" => "Mi Compra - Metalistería Fulsan",
    "carrito_h1" => "Mi Compra",
    "carrito_vacio_msg" => "Tu carrito está vacío.",
    "carrito_ver_productos" => "Ver Productos",
    "carrito_producto_lbl" => "Producto:",
    "carrito_detalles_lbl" => "Detalles:",
    "carrito_precio_lbl" => "Precio:",
    "carrito_eliminar_title" => "Eliminar producto",
    "carrito_total" => "Total:",
    "carrito_btn_vaciar" => "Vaciar Carrito",
    "carrito_btn_tramitar" => "Tramitar Pedido",
    "carrito_btn_comprar" => "Comprar",
    
    // SWEETALERT (Alertas JS)
    "swal_borrar_titulo" => "¿Estás seguro?",
    "swal_borrar_texto" => "Vas a quitar este producto de tu compra.",
    "swal_borrar_si" => "Sí, quitar",
    "swal_cancelar" => "Cancelar",
    "swal_vaciar_titulo" => "¿Vaciar carrito?",
    "swal_vaciar_texto" => "Se eliminarán todos los productos.",
    "swal_vaciar_si" => "Sí, vaciar todo",


    // CONOCENOS
    "conocenos_titulo_pag" => "Metalistería Fulsan - Conócenos",
    "empresa_titulo" => "Nuestra Empresa",
    "empresa_desc1" => "Ofrecemos una amplia gama de servicios tanto en fabricación como en carpintería metálica, permitiendo a nuestros clientes personalizar sus productos para adaptarnos a sus necesidades.",
    "empresa_desc2" => "Trabajamos para clientes a nivel local, con nuestra sede en Extrarradio Cortijo la Purisima, 2P, 18004 Granada, aunque también hemos trabajado a nivel nacional e internacional.",
    "nosotros_titulo" => "Nosotros",
    "nosotros_intro" => "Metalistería con más de 30 años de experiencia en el sector, distinguidos por la calidad de nuestros productos y la atención personalizada que ofrecemos a cada cliente.",
    "nosotros_historia" => "Fundada en 1985, anteriormente llamada Metalistería Aisan. En el año 2014 fue heredada por Fulgencio Sánchez bajo el nombre Metalistería Fulsan.",
    "nosotros_servicios" => "Nuestros clientes pertenecen a sectores muy diversos, como la construcción, la industria, los servicios, y el ámbito residencial, para los que realizamos todo tipo de estructuras, barandillas, puertas, rejas, y trabajos a medida en metal.",


    // POLITICA DE COOKIES
    "cookies_titulo_pag" => "Política de Cookies - Metalistería Fulsan",
    "cookies_h1" => "Política de Cookies",
    "cookies_fecha" => "Última actualización: 15 de Marzo de 2024",
    "cookies_intro" => "Este sitio web utiliza cookies propias y de terceros para mejorar la experiencia del usuario y analizar nuestros servicios.",
    "cookies_h2_1" => "1. ¿Qué son las cookies?",
    "cookies_p_1" => "Las cookies son pequeños archivos de texto que se descargan en su navegador cuando accede a determinados sitios web. Permiten almacenar y recuperar información sobre los hábitos de navegación de un usuario o de su equipo.",
    "cookies_h2_2" => "2. Tipos de Cookies que utilizamos",
    "cookies_li_1" => "<strong>Cookies técnicas:</strong> Son necesarias para el correcto funcionamiento de la web (ej. mantener la sesión o el carrito de compra).",
    "cookies_h2_3" => "3. Gestión de Cookies",
    "cookies_p_2" => "Puede usted permitir, bloquear o eliminar las cookies instaladas en su equipo mediante la configuración de las opciones del navegador instalado en su ordenador:",
    "cookies_p_3" => "Si decide desactivar las cookies, es posible que algunas funciones del sitio web no funcionen correctamente.",



    // DATOS DE ENVIO
    "envio_titulo_pag" => "Datos de Envío - Metalistería Fulsan",
    "envio_paso" => "Paso",
    "envio_step_1" => "Datos de envío",
    "envio_step_2" => "Método de Pago",
    "envio_step_3" => "Factura de Compra",
    "envio_h1" => "Datos de envío",
    "envio_lbl_nombre" => "Nombre Completo:",
    "envio_title_nombre" => "Solo se permiten letras y espacios",
    "envio_lbl_email" => "Email:",
    "envio_lbl_telefono" => "Teléfono:",
    "envio_title_telefono" => "Introduce un número de teléfono válido",
    "envio_lbl_calle" => "Calle / Dirección:",
    "envio_ph_calle" => "Ej: Calle Recogidas",
    "envio_lbl_num" => "Nº / Piso:",
    "envio_ph_num" => "Ej: 12",
    "envio_ph_piso" => "Ej: 3º A",
    "envio_lbl_cp" => "Código Postal / Localidad:",
    "envio_title_cp" => "El código postal debe tener 5 dígitos numéricos",
    "envio_ph_cp" => "Ej: 18001",
    "envio_lbl_notas" => "Notas para el repartidor (Opcional):",
    "envio_ph_notas" => "Ej: Llamar al telefonillo azul...",
    "envio_btn_volver" => "Volver atrás",
    "envio_btn_continuar" => "Continuar con el pago",

    // ADMIN - DETALLES VENTA
    "admin_detalles_titulo" => "Detalles Venta #",
    "admin_venta_no_encontrada" => "Venta no encontrada.",
    "admin_detalles_h1" => "Venta #",
    "admin_lbl_cliente" => "Cliente:",
    "admin_lbl_productos_pedido" => "Productos del pedido:",
    "admin_lbl_prod_nombre" => "Nombre Producto:",
    "admin_lbl_prod_precio" => "Precio Unitario:",
    "admin_lbl_prod_unidades" => "Unidades:",
    "admin_lbl_prod_subtotal" => "Subtotal:",
    "admin_lbl_importe_total" => "Importe Total:",
    "admin_btn_ir_usuario" => "Ir al usuario",
    "admin_swal_salir_guardar_tit" => "¿Salir sin guardar?",
    "admin_swal_salir_guardar_txt" => "Se perderán los cambios que no hayas guardado.",


    // EDITAR PERFIL
    "profile_edit_title" => "Editar Datos - Metalistería Fulsan",
    "profile_my_data" => "Mis datos",
    "profile_swal_success_tit" => "Datos actualizados",
    "profile_swal_success_txt" => "Tu perfil se ha guardado correctamente.",
    "profile_personal_data" => "Datos Personales",
    "profile_lbl_name" => "Nombre:",
    "profile_lbl_surname" => "Apellidos:",
    "profile_lbl_email" => "Correo electrónico:",
    "profile_lbl_dni" => "DNI/NIF/NIE:",
    "profile_lbl_phone" => "Teléfono:",
    
    // CAMBIO CONTRASEÑA
    "profile_btn_change_pass" => "Cambiar Contraseña",
    "profile_pass_instruction" => "Para establecer una nueva contraseña, verifica tu identidad.",
    "profile_lbl_current_pass" => "Contraseña actual:",
    "profile_btn_check" => "Comprobar",
    "profile_identity_verified" => "Identidad verificada.",
    "profile_lbl_new_pass" => "Nueva Contraseña:",
    "profile_ph_min_chars" => "Mínimo 4 caracteres",
    "profile_lbl_confirm_pass" => "Confirmar Nueva:",
    "profile_ph_repeat_pass" => "Repite la contraseña",
    "profile_btn_update_pass" => "Actualizar Contraseña",
    
    // DIRECCIÓN
    "profile_address_title" => "Dirección del domicilio",
    "profile_lbl_street" => "Calle:",
    "profile_lbl_num" => "Número:",
    "profile_lbl_floor" => "Piso / Puerta:",
    "profile_lbl_cp" => "Código Postal:",
    "profile_lbl_city" => "Población / Ciudad:",
    "profile_lbl_province" => "Provincia:",
    
    // BOTONES Y JS
    "profile_btn_exit" => "Salir",
    "profile_btn_save" => "Guardar cambios",
    "profile_js_err_dni_tit" => "Documento Incorrecto",
    "profile_js_err_dni_txt" => "El DNI/NIE tiene un formato o letra inválida. Corrígelo para guardar.",
    "profile_js_save_tit" => "¿Guardar cambios?",
    "profile_js_save_txt" => "¿Estás seguro de que quieres actualizar tus datos?",
    "profile_js_btn_yes" => "Sí, guardar",
    "profile_js_btn_cancel" => "Cancelar",
    "profile_js_exit_tit" => "¿Salir sin guardar?",
    "profile_js_exit_txt" => "Se perderán los cambios que no hayas guardado.",
    "profile_js_btn_exit" => "Sí, salir",
    
    // JS PASSWORD
    "profile_js_pass_correct" => "Contraseña correcta",
    "profile_js_pass_incorrect" => "La contraseña no es correcta.",
    "profile_js_pass_updated_tit" => "¡Actualizado!",
    "profile_js_pass_updated_txt" => "Nueva contraseña guardada correctamente.",
    "profile_js_attention" => "Atención",
    "profile_js_err_short" => "La contraseña debe tener al menos 4 caracteres.",
    "profile_js_err_match" => "Las contraseñas no coinciden.",
    "profile_js_err_empty" => "Por favor, escribe tu contraseña actual.",
);
?>