<?php
$lang = array(
    // MENU & FOOTER
    "conocenos" => "À propos",
    "productos" => "Produits",
    "carrito" => "Panier",
    "perfil" => "Mon Profil",
    "login" => "Connexion",
    "logout" => "Déconnexion",
    "registro" => "S'inscrire",
    "enlaces" => "Liens rapides",
    "contacto" => "Contact",
    "aviso" => "Mentions légales",
    "privacidad" => "Politique de confidentialité",
    "cookies" => "Politique de cookies",

    // PAGE D'ACCUEIL (INDEX)
    "index_titulo" => "Accueil Visiteur - Metalful",
    "hero_titulo" => "Métallerie avec plus de 30 ans d'expérience dans le secteur",
    "donde_estamos" => "Où nous trouver",
    "direccion" => "Extrarradio Cortijo la Purisima, 2P, 18004 Granada",
    "problemas_encontrar" => "Si vous avez du mal à nous trouver, appelez ce numéro :",
    "nuestros_productos" => "Nos Produits",
    "ver_mas" => "Voir plus",
    "faq_titulo" => "Foire Aux Questions",
    "faq_q1" => "Combien de temps faut-il pour que le produit arrive ?",
    "faq_a1" => "Le délai de livraison est généralement compris entre 3 et 7 jours selon le type de produit.",
    "faq_q2" => "Quelle est la zone de distribution des produits ?",
    "faq_a2" => "Nous livrons dans toute la province de Grenade et les environs.",
    "faq_q3" => "Comment pouvez-vous nous contacter ?",
    "faq_a3" => "Vous pouvez nous appeler au 652 921 960 ou nous écrire à metalfulsan@gmail.com.",

    // COOKIES BANNER
    "cookie_titulo" => "Confidentialité et Cookies.",
    "cookie_desc" => "Nous utilisons nos propres cookies pour améliorer votre expérience. Vous pouvez les accepter ou les refuser. Lisez notre",
    "cookie_link" => "politique de cookies",
    "cookie_rechazar" => "Refuser",
    "cookie_aceptar" => "Tout accepter",


    // MENTIONS LÉGALES
    "legal_titulo_pag" => "Mentions Légales - Metalistería Fulsan",
    "legal_h1" => "Mentions Légales",
    "legal_fecha" => "Dernière mise à jour : 15 mars 2024",
    "legal_intro" => "Conformément à l'article 10 de la loi 34/2002 du 11 juillet sur les services de la société de l'information et du commerce électronique (LSSICE), les données d'identification de l'entité sont exposées ci-dessous :",
    "legal_datos_t" => "1. Données d'identification",
    "legal_nombre_com" => "Nom commercial :",
    "legal_denom_soc" => "Dénomination sociale :",
    "legal_domicilio" => "Siège social :",
    "legal_correo" => "E-mail :",
    "legal_tel" => "Téléphone :",
    "legal_prop_t" => "2. Propriété Intellectuelle",
    "legal_prop_desc" => "Le code source, les conceptions graphiques, les images, les photographies, les sons, les animations, le logiciel, les textes, ainsi que les informations et les contenus recueillis sur ce site web sont protégés par la législation espagnole sur les droits de propriété intellectuelle et industrielle en faveur de Metalistería Fulsan S.L.",
    "legal_prot_t" => "3. Protection des Données Personnelles",
    "legal_prot_desc" => "Dans le cadre du respect de la législation en vigueur, contenue dans la loi organique 15/1999 du 13 décembre sur la protection des données à caractère personnel (LOPD), dont l'objet est de garantir et de protéger, en ce qui concerne le traitement des données personnelles, les libertés et droits fondamentaux des personnes physiques, Metalistería Fulsan informe les utilisateurs que les données saisies dans les formulaires de contact seront stockées dans un fichier automatisé appartenant à l'entreprise.",
    "legal_ley_t" => "4. Législation Applicable",
    "legal_ley_desc" => "La loi applicable en cas de litige ou de conflit d'interprétation des termes qui composent ces mentions légales, ainsi que toute question liée aux services du présent portail, sera la loi espagnole.",


    // PANIER
    "carrito_titulo_pag" => "Mon Panier - Metalistería Fulsan",
    "carrito_h1" => "Mon Panier",
    "carrito_vacio_msg" => "Votre panier est vide.",
    "carrito_ver_productos" => "Voir les produits",
    "carrito_producto_lbl" => "Produit :",
    "carrito_detalles_lbl" => "Détails :",
    "carrito_precio_lbl" => "Prix :",
    "carrito_eliminar_title" => "Supprimer le produit",
    "carrito_total" => "Total :",
    "carrito_btn_vaciar" => "Vider le panier",
    "carrito_btn_tramitar" => "Passer la commande",
    "carrito_btn_comprar" => "Acheter",

    // SWEETALERT
    "swal_borrar_titulo" => "Êtes-vous sûr ?",
    "swal_borrar_texto" => "Vous allez retirer ce produit de votre panier.",
    "swal_borrar_si" => "Oui, retirer",
    "swal_cancelar" => "Annuler",
    "swal_vaciar_titulo" => "Vider le panier ?",
    "swal_vaciar_texto" => "Tous les produits seront supprimés.",
    "swal_vaciar_si" => "Oui, tout vider",


    // À PROPOS
    "conocenos_titulo_pag" => "Metalistería Fulsan - À propos",
    "empresa_titulo" => "Notre Entreprise",
    "empresa_desc1" => "Nous offrons une large gamme de services tant dans la fabrication que dans la menuiserie métallique, permettant à nos clients de personnaliser leurs produits pour s'adapter à leurs besoins.",
    "empresa_desc2" => "Nous travaillons pour des clients au niveau local, avec notre siège à Extrarradio Cortijo la Purisima, 2P, 18004 Granada, bien que nous ayons également travaillé au niveau national et international.",
    "nosotros_titulo" => "À propos de nous",
    "nosotros_intro" => "Métallerie avec plus de 30 ans d'expérience dans le secteur, distingués par la qualité de nos produits et l'attention personnalisée que nous offrons à chaque client.",
    "nosotros_historia" => "Fondée en 1985, anciennement appelée Metalistería Aisan. En 2014, elle a été héritée par Fulgencio Sánchez sous le nom de Metalistería Fulsan.",
    "nosotros_servicios" => "Nos clients appartiennent à des secteurs très divers, tels que la construction, l'industrie, les services et le secteur résidentiel, pour lesquels nous réalisons toutes sortes de structures, garde-corps, portes, grilles et travaux sur mesure en métal.",


    // POLITIQUE DE COOKIES
    "cookies_titulo_pag" => "Politique de Cookies - Metalistería Fulsan",
    "cookies_h1" => "Politique de Cookies",
    "cookies_fecha" => "Dernière mise à jour : 15 mars 2024",
    "cookies_intro" => "Ce site web utilise ses propres cookies et des cookies tiers pour améliorer l'expérience utilisateur et analyser nos services.",
    "cookies_h2_1" => "1. Que sont les cookies ?",
    "cookies_p_1" => "Les cookies sont de petits fichiers texte qui sont téléchargés sur votre navigateur lorsque vous accédez à certains sites web. Ils permettent de stocker et de récupérer des informations sur les habitudes de navigation d'un utilisateur ou de son équipement.",
    "cookies_h2_2" => "2. Types de Cookies que nous utilisons",
    "cookies_li_1" => "<strong>Cookies techniques :</strong> Ils sont nécessaires au bon fonctionnement du site web (par exemple, maintenir la session ou le panier d'achat).",
    "cookies_h2_3" => "3. Gestion des Cookies",
    "cookies_p_2" => "Vous pouvez autoriser, bloquer ou supprimer les cookies installés sur votre ordinateur en configurant les options du navigateur installé sur votre ordinateur :",
    "cookies_p_3" => "Si vous décidez de désactiver les cookies, certaines fonctions du site web peuvent ne pas fonctionner correctement.",


    // DONNÉES D'EXPÉDITION
    "envio_titulo_pag" => "Données d'expédition - Metalistería Fulsan",
    "envio_paso" => "Étape",
    "envio_step_1" => "Données d'expédition",
    "envio_step_2" => "Méthode de paiement",
    "envio_step_3" => "Facture d'achat",
    "envio_h1" => "Données d'expédition",
    "envio_lbl_nombre" => "Nom complet :",
    "envio_title_nombre" => "Seules les lettres et les espaces sont autorisés",
    "envio_lbl_email" => "E-mail :",
    "envio_lbl_telefono" => "Téléphone :",
    "envio_title_telefono" => "Veuillez entrer un numéro de téléphone valide",
    "envio_lbl_calle" => "Rue / Adresse :",
    "envio_ph_calle" => "Ex : Rue de la Paix",
    "envio_lbl_num" => "N° / Étage :",
    "envio_ph_num" => "Ex : 12",
    "envio_ph_piso" => "Ex : 3ème étage",
    "envio_lbl_cp" => "Code postal / Ville :",
    "envio_title_cp" => "Le code postal doit être numérique",
    "envio_ph_cp" => "Ex : 75001",
    "envio_lbl_notas" => "Notes pour le livreur (Optionnel) :",
    "envio_ph_notas" => "Ex : Sonnez à l'interphone bleu...",
    "envio_btn_volver" => "Retour",
    "envio_btn_continuar" => "Continuer vers le paiement",


    // ADMIN - DÉTAILS DE LA VENTE
    "admin_detalles_titulo" => "Détails Vente #",
    "admin_venta_no_encontrada" => "Vente introuvable.",
    "admin_detalles_h1" => "Vente #",
    "admin_lbl_cliente" => "Client :",
    "admin_lbl_productos_pedido" => "Produits de la commande :",
    "admin_lbl_prod_nombre" => "Nom du produit :",
    "admin_lbl_prod_precio" => "Prix unitaire :",
    "admin_lbl_prod_unidades" => "Unités :",
    "admin_lbl_prod_subtotal" => "Sous-total :",
    "admin_lbl_importe_total" => "Montant total :",
    "admin_btn_ir_usuario" => "Aller à l'utilisateur",
    "admin_swal_salir_guardar_tit" => "Quitter sans enregistrer ?",
    "admin_swal_salir_guardar_txt" => "Les modifications non enregistrées seront perdues.",


    // MODIFIER PROFIL
    "profile_edit_title" => "Modifier le profil - Metalistería Fulsan",
    "profile_my_data" => "Mes données",
    "profile_swal_success_tit" => "Données mises à jour",
    "profile_swal_success_txt" => "Votre profil a été enregistré avec succès.",
    "profile_personal_data" => "Données personnelles",
    "profile_lbl_name" => "Prénom :",
    "profile_lbl_surname" => "Nom :",
    "profile_lbl_email" => "E-mail :",
    "profile_lbl_dni" => "CNI/NIF :",
    "profile_lbl_phone" => "Téléphone :",
    
    // CHANGEMENT DE MOT DE PASSE
    "profile_btn_change_pass" => "Changer le mot de passe",
    "profile_pass_instruction" => "Pour définir un nouveau mot de passe, vérifiez votre identité.",
    "profile_lbl_current_pass" => "Mot de passe actuel :",
    "profile_btn_check" => "Vérifier",
    "profile_identity_verified" => "Identité vérifiée.",
    "profile_lbl_new_pass" => "Nouveau mot de passe :",
    "profile_ph_min_chars" => "Minimum 4 caractères",
    "profile_lbl_confirm_pass" => "Confirmer le nouveau :",
    "profile_ph_repeat_pass" => "Répétez le mot de passe",
    "profile_btn_update_pass" => "Mettre à jour",
    
    // ADRESSE
    "profile_address_title" => "Adresse du domicile",
    "profile_lbl_street" => "Rue :",
    "profile_lbl_num" => "Numéro :",
    "profile_lbl_floor" => "Étage / Porte :",
    "profile_lbl_cp" => "Code postal :",
    "profile_lbl_city" => "Ville :",
    "profile_lbl_province" => "Province :",
    
    // BOUTONS ET JS
    "profile_btn_exit" => "Quitter",
    "profile_btn_save" => "Enregistrer",
    "profile_js_err_dni_tit" => "Document invalide",
    "profile_js_err_dni_txt" => "Le format du document est invalide. Veuillez le corriger.",
    "profile_js_save_tit" => "Enregistrer les modifications ?",
    "profile_js_save_txt" => "Êtes-vous sûr de vouloir mettre à jour vos données ?",
    "profile_js_btn_yes" => "Oui, enregistrer",
    "profile_js_btn_cancel" => "Annuler",
    "profile_js_exit_tit" => "Quitter sans enregistrer ?",
    "profile_js_exit_txt" => "Les modifications non enregistrées seront perdues.",
    "profile_js_btn_exit" => "Oui, quitter",
    
    // JS MOT DE PASSE
    "profile_js_pass_correct" => "Mot de passe correct",
    "profile_js_pass_incorrect" => "Mot de passe incorrect.",
    "profile_js_pass_updated_tit" => "Mis à jour !",
    "profile_js_pass_updated_txt" => "Nouveau mot de passe enregistré avec succès.",
    "profile_js_attention" => "Attention",
    "profile_js_err_short" => "Le mot de passe doit contenir au moins 4 caractères.",
    "profile_js_err_match" => "Les mots de passe ne correspondent pas.",
    "profile_js_err_empty" => "Veuillez entrer votre mot de passe actuel.",
);
?>